#!/bin/bash
# Copyright 2014 R. RIGNIER
#This file is part of ltsp-osdeploy.
#
#    Foobar is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    ltsp-osdeploy is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with ltsp-osdeploy.  If not, see <http://www.gnu.org/licenses/>.
 

#python 2.7 needs correct LANG env var
#same language set should be set in /usr/share/pyddlaj/settings/__init.py__ 
if [ -r /etc/default/locale ]; then
	. /etc/default/locale
fi

export LANG
/usr/bin/pyddlaj

ret=$?

#on normal exit we reboot computer
if [ $ret = 0 ]; then
	init 6
else
	echo "an error occured. launch Console login"
	echo
	/bin/login
fi
