#!/bin/bash

## Copyright (c) 2003-2012 Tissoires Jean-François & Benjamin,  jftissoires@gmail.com
## Cdrom Outil Système Complet d'Assistance Réseau: OSCAR
## Ce programme est sous Licence Publique Générale GNU publiée par la Free Software Foundation.


# lancement par l'autorun de ce fichier
#----------------------------------------------------------------------------------------------------
#----------------------------------------------------------------------------------------------------
#-----------------------------------------------------------------------------------------------------
boite_depart()
{
numero_version=`cat /usr/share/oscar/usr/numero_version_oscar`
	DIALOGRC="/etc/dialogmenu_bloque" dialog --colors\
	--backtitle "`cat /etc/banniere_oscar`" \
	--cancel-label "Eteindre l'ordinateur" --ok-label "Démarrer OSCAR" --extra-button --extra-label "Restaurer ce poste" \
	--menu "\Zb\Z4   Bienvenue dans l'\Z3O\Z4util de\Z3 S\Z4auvegarde\Z3 C\Z4omplet d'\Z3A\Z4ssistance \Z3R\Z4éseau " 7 76 0 \
	"" " " \
	"" "\Zb\Z1      Soyez vigilant ce logiciel peut détruire un poste ! \\Zn " \
	"" " " \
	"" "\Zb\Z3                   OSCAR  \Z4version $numero_version " \
	"" " " \
	"" " " \
	"" "\Z2Copyright (c) 2004 (Tissoires Jean-François & Benjamin)\Zb\Zn " \
	"" "\Zb\Z1O\Z3util\Zb\Z1 S\Z3ystème \Zb\Z1C\Z3omplet d'\Zb\Z1A\Z3ssistance\Zb\Z1 R\Z3éseau, \Zb\Z1OSCAR" \
	"" "\Zb\Z1Rapide \Z3de\Zb\Z1 S\Z3auvegarde aux\Zb\Z1 O\Z3rdinateurs et\Zb\Z1 S\Z3ystèmes, \Zb\Z1RapideSOS " \
	"" "\Z2jftissoires@gmail.com \Zn " \
	"" " "
      case $? in
	    0)	autoriser ;;
	    3)  rst ;;
	    1)	eteindre_le_poste;;
	    255) boite_depart ;;
	esac
}
#-----------------------------------------------------------------------------------------------------
#-----------------------------------------------------------------------------------------------------
autoriser()
{
boite_sauver
		# rm -f /etc/demarrage_cdrom	# à vérifier
		# rm -f /etc/demarrage_cdcache	# à vérifier
		# rm -f /etc/demarrage_usb 	# ne pas supprimer: besoin pour les autres pages écrans
		
		## clé USB
		if ( test -e /mnt/cdrom/oscar.igz )	# démarrage par clé USB
		then
			echo "" > /etc/demarrage_usb
			echo "" > /etc/cdrom_ejecte	# cd ejecté
		fi
				
		if ( test -e /livemnt/boot/isolinux/oscar ) ###	Si démarrage par cdrom ou cdrom monté:
		then
			if ! ( test -e /etc/cdrom_ejecte ) ###	Si démarrage par cdrom ou cdrom monté:
			then
				echo "" > /etc/demarrage_cdrom
	# a voir pour recup-depuis-cd-dvd:
			else	# démarrage par le poste
				rm -f /etc/demarrage_cdrom
				rm -f /etc/gpm_lance	# pour sysrcd avec internet
				echo "" > /etc/cdrom_ejecte	# cd ejecté
			fi
		fi
		
		if ( test -e /etc/client_minimal ) ## le poste est démarré avec le cd oscar minimal # client minimal fsscript_cli.sh de livecd:
		then
			echo "" > /etc/demarrage_cdoscar_minimal
		fi
		if ( test -e /mnt/livecd.squashfs ) || ( test -e /mnt/sysrcd.dat ) ## le poste est démarré avec option docache ou cdcache:
		then
			echo "" > /etc/demarrage_cdcache
			echo "" > /etc/demarrage_cdrom
			if ( test -e /etc/client_minimal ) ## le poste est démarré avec le cd oscar minimal # client minimal fsscript_cli.sh de livecd:
			then
				echo "" > /etc/demarrage_cdoscar_minimal
			fi
			if ( test -e /etc/demarrage_usb )	# démarrage par clé USB en mémoire
			then
				umount /mnt/cdrom	#	pour pouvoir enlever la clé
			fi
		fi
		installe_ethernet
		if ! ( test -e /etc/mi_co )
		then
		    echo "" > /etc/mi_co
		fi
		if ( test -e /etc/demarrage_usb )	# démarrage par clé USB en mémoire
		then
			if ( test -e /etc/demarrage_cdcache )	# démarrage par clé USB en mémoire
			then
				if ! ( test -e /etc/cle_usb_enlevee )	# démarrage par clé USB en mémoire
				then
					umount /mnt/cdrom
					depart_info_enlever_cle_usb
					echo "" > /etc/cle_usb_enlevee	# pour info seulement la premiere console
				fi
			fi
		fi
		if ( test -e /etc/X11/xorg.conf )	# installer le clavier fr pour WindowMaker avec sysrcd
		then
		    grep -ci "\"XkbLayout\" \"\"" /etc/X11/xorg.conf > /tmp/tempfile
		    nombre_fr=`cat /tmp/tempfile`
		    rm -f /tmp/tempfile
		    if [ "$nombre_fr" = "1" ]
		    then
			perl -pi -e 's/\"XkbLayout\" \"\"/\"XkbLayout\" \"fr\"/g;' /etc/X11/xorg.conf
		    fi
		fi
		oscar
		exit
}
#----------------------------------------------------------------------------------------------------
#----------------------------------------------------------------------------------------------------
eteindre_le_poste()
{
	DIALOGRC="/etc/dialogmenu_bloque" dialog --colors \
	--backtitle "`cat /etc/banniere_oscar`" \
	--title " Le poste s'éteint " \
	--infobox "\n\n\n\Zb\Z2      Patientez le poste s'éteint proprement... \n\n\n\n" 0 0
	
halt
sleep 10
exit
}
#----------------------------------------------------------------------------------------------------
#----------------------------------------------------------------------------------------------------
boite_sauver()
{
	rm -f /tmp/tempfile
	verif=`cat /usr/share/oscar/bin/fichier_a  `
	DIALOGRC="/etc/dialogmenu_bloque" dialog --colors\
	--backtitle "`cat /etc/banniere_oscar`" \
	--cancel-label "Annuler"  --title " Mot de passe administrateur " \
	--passwordbox "\n\n\Zb\Z1   ATTENTION pour utiliser ce menu il faut être administrateur réseau \
	  \n \n  \n \
	\Z2Entrez le\Z4 mot de passe\Z2 administrateur de ce poste: \n " 0 0 2> /tmp/tempfile
	reponse=`cat /tmp/tempfile`
	rm -f /tmp/tempfile
	if ( test -e $reponse )
	then
	    boite_depart
	elif  [ $reponse = $verif ]
	then
	    echo "oscar" > /etc/oscar
	    return
	else
	    boite_sauver
	fi
}
#----------------------------------------------------------------------------------------------------
#----------------------------------------------------------------------------------------------------
#                   BOUCLE PRINCIPALE
#----------------------------------------------------------------------------------------------------
main() # boucle principale
{
/usr/share/oscar/usr/version_theme_oscar
	# lancer dans la premiere console
	tty | grep 1 > /dev/null
	if [ $? = 0 ] 
	then
	    	rm -f /etc/demarrage_cdrom
	    	rm -f /etc/demarrage_cdcache
	    	if ( test -e /mnt/livecd.squashfs ) || ( test -e /mnt/sysrcd.dat ) ## le poste est démarré avec le cdrom:
		then
			echo "" > /etc/demarrage_cdrom
			echo "" > /etc/demarrage_cdcache	#	pour pouvoir démonter le cédérom dans rst
		fi
		
	    	rm -f /etc/demarrage_usb
		if ( test -e /mnt/cdrom/oscar.igz )	# démarrage par clé USB
		then
			echo "" > /etc/demarrage_usb
			umount /mnt/cdrom	#	pour pouvoir enlever la clé
		fi

		echo "" > /tmp/menuoscar_client
		rst
		halt
	fi
boite_depart
rm -f /tmp/historique
rm -f /etc/partition_win_active_*	#initialise les répertoires win partagés
}
#---------------------------------------------------------------------------------------------------
PATH="/usr/share/oscar/bin:$PATH"
main