07f2help.lss
0c                O0butil 0cS0bysteme 0cC0bomplet d'0cA0bssistance 0cR0beseau (c)07

0foscar video 07ou (0foscar novideo07) pour utiliser (ou non) l'interface graphique

0CPar defaut07 la commande est 0Foscar cdcache07 en appuyant sur 0CEntrer07
0Fcdcache07    Option pour enregistrer en memoire le cdrom et pouvoir l'enlever,
           il faut 150Mo disponible en RAM.

0C*07 Autres commandes (voir aussi l'aide avec les touches 0FF307 et 0FF407),
  au 0Fboot: _07    puis 0CEntrer07
0Fmemtest07    memtest+ (teste les memoires)
0Franish07     Ranish Partition Manager
0Faida07       Outil de diagnostic de l'ordinateur
0Fdisk107      Boot de demarrage sur le disque dur de l'ordinateur ou 0Fdisk207.
