07




0c                O0butil 0cS0bysteme 0cC0bomplet d'0cA0bssistance 0cR0beseau (c)07



Demarrages possibles (voir les options 0eF307 ou 0eF407) :
0foscar          07ou 0Fclient07 ou 0Frestaure07
0foscar docache  07Pour enregistrer en memoire le cederom et pouvoir l'enlever,
0f               07option par defaut : il faut 512Mo disponible en RAM
0fnet            07Pour le demarrage par le reseau par

0foscar xfce 07ou (0foscar noxfce07) pour utiliser (ou non) l'interface graphique

0C*07 Autres commandes (voir aussi l'aide avec les touches 0FF307 et 0FF407):
0Fmemtest07    memtest+ (teste les memoires)
0Fgag07        Interface graphique de gestion du demarrage
0Franish07     Ranish Partition Manager
0Fhdt07        Outil de detection du materiel
0Fdban07       Supprime toutes les donnees de l'ordinateur efface les disques durs
0Fmhdd07       Outils de test des disques durs
0Fntpass07     Edition des mots de passe Windows sur partition NTFS
0Ffreedos07    DOS libre
0Fdisk107      Boot de demarrage sur le disque dur de l'ordinateur ou 0Fdisk207



0C07