07f3kern.lss

0C*07 Autres commandes, au 0Fboot: _07  puis 0CEntrer07  :
0Fgag07       GAG (Graphical Boot Manager)
0Fdban07      Supprime toutes les donnees de l'ordinateur, efface les disques durs!
0Ffreedos07   FreeDos ( DOS programs from a free OS)
0Ffloppy07    Boot from the floppy disk of the computer
0Fntpass07    Edit Windows login passwords even on NTFS disks

0C*07 La commande de definition d'ecran peut etre suivie aussi de ces options:
0Fusbstick07  Use this option if you boot from an USB-stick. The system
   will try to mount the USB device, and it will boot from this device.

0C*07 In case of boot trouble, you may try one or more of these options :
0Facpi=on07   Different from APIC, 0CACPI07 stands for "advanced configuration and
   power interface". 0CACPI07 is required for some legacy-free systems, but can
   potentially cause problems on others. Try it on recent systems.
0Fide=nodma07 Forcefully disable 0CDMA07 for malfunctioning IDE devices.
0Fnonet07     Prevents 0Cnetwork07 device auto-detection at boot time.
0Fnoscsi07    Prevents 0CSCSI07 device auto-detection at boot time.
0Fnodetect07  Prevents generic auto-detection at boot time.
0Fdopcmcia07  Detects the pcmcia hardaware.

