#!/bin/bash

## Copyright (c) 2003-2012 Tissoires Jean-François & Benjamin,  jftissoires@gmail.com
## Outil Système Complet d'Assistance Réseau: OSCAR
## Rapide de Sauvegarde aux Ordinateurs et Systèmes: RapideSOS
## Ce programme est sous Licence Publique Générale GNU publiée par la Free Software Foundation.

#----------------------------------------------------------------------------------------------------
#

# Gestion des couleurs

#    fin=\033[0;m
#    noir=\033[0;30m
#    rouge=\033[0;31m
#    vert=\033[0;32m
#    marron=\033[0;33m
#    bleu=\033[0;34m
#    violet=\033[0;35m
#    cyan=\033[0;36m
#    gris=\033[0;37m
#    grisf=\033[1;30m
#    rougec=\033[1;31m
#    vertc=\033[1;32m
#    jaune=\033[1;33m
#    bleuc=\033[1;34m
#    violetc=\033[1;35m
#    cyanc=\033[1;36m
#    blanc=\033[1;37m
#-----------------------------------------------------------------------------------------------------
#                   BOUCLE PRINCIPALE
#-----------------------------------------------------------------------------------------------------
PATH="/usr/share/oscar/bin:$PATH"
numero_version=`cat /usr/share/oscar/usr/numero_version_oscar`
if ! ( test -e /etc/banniere_oscar )
then
    echo "\Zb\Z1    O\Z3util\Z1 S\Z3ystème\Z1 C\Z3omplet d'\Z1A\Z3ssistance \Z1R\Z3éseau, \Z1 OSCAR  \Z4$numero_version " > /etc/banniere_oscar
fi    
cp -f /usr/share/oscar/usr/exec_dialog_src /etc/exec_dialog_src 2>/dev/null
cp -f /usr/share/oscar/usr/dialogrc /etc/dialogrc 2>/dev/null
cp -f /usr/share/oscar/usr/dialogmenu_bloque /etc/dialogmenu_bloque 2>/dev/null
# setterm -powerdown	# setterm -powersave off   # supprime l'écran de veille
setterm -msg off	# n'affiche pas les messages d'erreurs

